
comment_params = {
    "WebIdLastTime": "1696040888",
    "aid": "1988",
    "app_language": "ja-JP",
    "app_name": "tiktok_web",
    "aweme_id": str,
    "browser_language": "vi-VN",
    "browser_name": "Mozilla",
    "browser_online": "true",
    "browser_platform": "Win32",
    "browser_version": "5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
    "channel": "tiktok_web",
    "cookie_enabled": "true",
    "count": int,
    "current_region": "JP",
    "cursor": int,
    "data_collection_enabled": "true",
    "device_id": str,
    "device_platform": "web_pc",
    "enter_from": "tiktok_web",
    "focus_state": "false",
    "fromWeb": "1",
    "from_page": "video",
    "is_fullscreen": "false",
    "is_non_personalized": "false",
    "is_page_visible": "true",
    "os": "windows",
    "priority_region": "VN",
    "referer":"",
    "region": "VN",
    "screen_height": int,
    "screen_width": int,
    "tz_name": "Etc/GMT-7",
    "user_is_login": "true",
    "webcast_language": "vi-VN",
    'msToken': str,
    'X-Bogus': 'DFSzswVORFUANComt1lFJj4Us/VN',
    '_signature': '_02B4Z6wo00001-JiTvQAAIDAkmV.vBAv8AfiYkpAAJ5la3',
}

reply_params = {
    "WebIdLastTime": "1696040888",
    "aid": "1988",
    "app_language": "ja-JP",
    "app_name": "tiktok_web",
    "browser_language": "vi-VN",
    "browser_name": "Mozilla",
    "browser_online": "true",
    "browser_platform": "Win32",
    "browser_version": "5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36",
    "channel": "tiktok_web",
    "comment_id": str,
    "cookie_enabled": "true",
    "count": int,
    "current_region": "JP",
    "cursor": int,
    "data_collection_enabled": "true",
    "device_id": str,
    "device_platform": "web_pc",
    "enter_from": "tiktok_web",
    "focus_state": "true",
    "fromWeb": "1",
    "from_page": "video",
    "is_fullscreen": "false",
    "is_page_visible": "true",
    "item_id": str, # id of video
    "os": "windows",
    "priority_region": "VN",
    "referer": "https://www.tiktok.com/",
    "region": "VN",
    "root_referer": "https://www.tiktok.com/",
    "screen_height": int,
    "screen_width": int,
    "tz_name": "Etc/GMT-7",
    "user_is_login": "true",
    "webcast_language": "vi-VN",
    "msToken": str,
    'X-Bogus': 'DFSzswVORFUANComt1lFJj4Us/VN',
    '_signature': '_02B4Z6wo00001-JiTvQAAIDAkmV.vBAv8AfiYkpAAJ5la3',
}